### PR TITLE
Upgrade rails, static seeds, add new currency data.

### PR DESCRIPTION
**Pull request by JeffLuckett**

### CODE REVIEW

**Comment by moort** [comment]
:shipit:

**Comment by bderusha** [comment]
Can we tag this version and the old version?

**Comment by bderusha** [comment]
Is there a need to actually? Hmm.  I guess the real question is "does this upgrade impact the current test if someone wanted to use it?"

**Comment by JeffLuckett** [comment]
These changes upgrade Ruby and Rails, add a few attrs to Currency and makes the seeds static.  We can still use the same code base for the "old" test spec, so I don't think there's a need for a tag.

**Pull request merged**
